<template>
  <component :is="iconComponent" v-if="iconComponent" v-bind="$attrs" />
  <FileIcon v-else v-bind="$attrs" />
</template>

<script setup>
import { computed, useAttrs } from 'vue'

defineOptions({ inheritAttrs: false })

const attrs = useAttrs()
import {
  HomeIcon, SettingIcon, UserIcon, UserCircleIcon, ViewModuleIcon,
  MenuIcon, NotificationIcon, MoonIcon, SunnyIcon, SwapIcon,
  EditIcon, DeleteIcon, SearchIcon, AddIcon, MinusIcon,
  CloseIcon, CheckIcon, CheckCircleIcon, CheckCircleFilledIcon,
  ErrorCircleIcon, ErrorCircleFilledIcon, InfoCircleFilledIcon,
  HelpCircleFilledIcon, CloseCircleFilledIcon,
  ChevronDownIcon, ChevronLeftIcon, ChevronRightIcon, ChevronUpIcon,
  ChevronLeftDoubleIcon, ChevronRightDoubleIcon,
  ArrowUpIcon, ArrowDownIcon, RollbackIcon,
  UploadIcon, DownloadIcon, RefreshIcon,
  ShareIcon, StarIcon, StarFilledIcon,
  ImageIcon, FileIcon, FolderIcon, FolderOpenIcon,
  LinkIcon, FileCopyIcon, PrintIcon,
  LocationIcon, LockOnIcon, LockOffIcon, SecuredIcon,
  CallIcon, ChatIcon, ChatBubbleIcon, MailIcon,
  BrowseIcon, BrowseOffIcon,
  DiscountIcon, TicketIcon, ShopIcon, MoneyIcon, CartIcon, GiftIcon,
  ChartIcon, DashboardIcon, ChartBarIcon, ChartPieIcon, ChartLineIcon,
  TimeIcon, AlarmIcon, CalendarIcon,
  ViewListIcon, ViewAgendaIcon, UnfoldMoreIcon, UnfoldLessIcon,
  GestureClickIcon, FilterIcon, OrderDescendingIcon, OrderAscendingIcon,
  VideoIcon, PlayCircleIcon, PauseCircleIcon,
  EarphoneIcon, MicrophoneIcon, PoweroffIcon,
  DesktopIcon, MobileIcon, CpuIcon,
  CompassIcon, BookOpenIcon, BookIcon,
  HighlightIcon, FormatPainterIcon, CutIcon,
  FullscreenIcon, EllipsisIcon, ToolsIcon,
  BuildingIcon, EducationIcon,
  BookmarkIcon,
  ThumbUpIcon, ThumbUpFilledIcon, UsergroupIcon, HelpCircleIcon,
} from 'tdesign-icons-vue-next'

const props = defineProps({
  name: { type: String, default: '' }
})

// Map TDesign icon stems to their component references
const iconMap = {
  'home': HomeIcon,
  'setting': SettingIcon,
  'user': UserIcon,
  'user-circle': UserCircleIcon,
  'view-module': ViewModuleIcon,
  'menu': MenuIcon,
  'notification': NotificationIcon,
  'moon': MoonIcon,
  'sunny': SunnyIcon,
  'swap': SwapIcon,
  'edit': EditIcon,
  'delete': DeleteIcon,
  'search': SearchIcon,
  'add': AddIcon,
  'minus': MinusIcon,
  'close': CloseIcon,
  'check': CheckIcon,
  'check-circle': CheckCircleIcon,
  'check-circle-filled': CheckCircleFilledIcon,
  'error-circle': ErrorCircleIcon,
  'error-circle-filled': ErrorCircleFilledIcon,
  'info-circle-filled': InfoCircleFilledIcon,
  'help-circle-filled': HelpCircleFilledIcon,
  'help-circle': HelpCircleIcon,
  'close-circle-filled': CloseCircleFilledIcon,
  'close-circle': CloseCircleFilledIcon,
  'chevron-down': ChevronDownIcon,
  'chevron-left': ChevronLeftIcon,
  'chevron-right': ChevronRightIcon,
  'chevron-up': ChevronUpIcon,
  'chevron-left-double': ChevronLeftDoubleIcon,
  'chevron-right-double': ChevronRightDoubleIcon,
  'arrow-up': ArrowUpIcon,
  'arrow-down': ArrowDownIcon,
  'rollback': RollbackIcon,
  'upload': UploadIcon,
  'download': DownloadIcon,
  'refresh': RefreshIcon,
  'share': ShareIcon,
  'star': StarIcon,
  'star-filled': StarFilledIcon,
  'image': ImageIcon,
  'file': FileIcon,
  'folder': FolderIcon,
  'folder-open': FolderOpenIcon,
  'link': LinkIcon,
  'file-copy': FileCopyIcon,
  'print': PrintIcon,
  'location': LocationIcon,
  'lock-on': LockOnIcon,
  'lock-off': LockOffIcon,
  'secured': SecuredIcon,
  'call': CallIcon,
  'chat': ChatIcon,
  'chat-bubble': ChatBubbleIcon,
  'mail': MailIcon,
  'browse': BrowseIcon,
  'browse-off': BrowseOffIcon,
  'discount': DiscountIcon,
  'ticket': TicketIcon,
  'shop': ShopIcon,
  'money': MoneyIcon,
  'cart': CartIcon,
  'gift': GiftIcon,
  'chart': ChartIcon,
  'dashboard': DashboardIcon,
  'chart-bar': ChartBarIcon,
  'chart-pie': ChartPieIcon,
  'chart-line': ChartLineIcon,
  'time': TimeIcon,
  'alarm': AlarmIcon,
  'calendar': CalendarIcon,
  'view-list': ViewListIcon,
  'view-agenda': ViewAgendaIcon,
  'unfold-more': UnfoldMoreIcon,
  'unfold-less': UnfoldLessIcon,
  'gesture-click': GestureClickIcon,
  'filter': FilterIcon,
  'order-descending': OrderDescendingIcon,
  'order-ascending': OrderAscendingIcon,
  'video': VideoIcon,
  'play-circle': PlayCircleIcon,
  'pause-circle': PauseCircleIcon,
  'earphone': EarphoneIcon,
  'microphone': MicrophoneIcon,
  'poweroff': PoweroffIcon,
  'desktop': DesktopIcon,
  'mobile': MobileIcon,
  'cpu': CpuIcon,
  'compass': CompassIcon,
  'books': BookOpenIcon,
  'book-open': BookOpenIcon,
  'highlight': HighlightIcon,
  'format-color': FormatPainterIcon,
  'cut': CutIcon,
  'fullscreen': FullscreenIcon,
  'ellipsis': EllipsisIcon,
  'tools': ToolsIcon,
  'building': BuildingIcon,
  'education': EducationIcon,
  'bookmark': BookmarkIcon,
  'thumb-up': ThumbUpIcon,
  'thumb-up-filled': ThumbUpFilledIcon,
  'usergroup': UsergroupIcon,
  // Common dashboard/admin extras
  'app': HomeIcon,
  'user-setting': SettingIcon,
  'cloudy-day': SunnyIcon,
  'preview': BrowseIcon,
  // 菜单历史图标（el-icon-* 旧命名 → 本地 TDesign 图标，避免触发 iconfont CDN 加载，离线/内网可用）
  'house': HomeIcon,
  'el-icon-alarm-clock': AlarmIcon,
  'el-icon-coin': MoneyIcon,
  'el-icon-copy-document': FileCopyIcon,
  'el-icon-date': CalendarIcon,
  'el-icon-document': FileIcon,
  'el-icon-document-copy': FileCopyIcon,
  'el-icon-edit-outline': EditIcon,
  'el-icon-folder-opened': FolderOpenIcon,
  'el-icon-help': HelpCircleIcon,
  'el-icon-link': LinkIcon,
  'el-icon-location': LocationIcon,
  'el-icon-magic-stick': ToolsIcon,
  'el-icon-menu': MenuIcon,
  'el-icon-message-solid': ChatBubbleIcon,
  'el-icon-mic': MicrophoneIcon,
  'el-icon-microphone': MicrophoneIcon,
  'el-icon-notebook-1': BookIcon,
  'el-icon-notebook-2': BookIcon,
  'el-icon-odometer': DashboardIcon,
  'el-icon-paperclip': LinkIcon,
  'el-icon-phone': CallIcon,
  'el-icon-phone-outline': CallIcon,
  'el-icon-picture': ImageIcon,
  'el-icon-pie-chart': ChartPieIcon,
  'el-icon-position': LocationIcon,
  'el-icon-question': HelpCircleIcon,
  'el-icon-receiving': DownloadIcon,
  'el-icon-s-custom': UserCircleIcon,
  'el-icon-s-data': ChartBarIcon,
  'el-icon-search': SearchIcon,
  'el-icon-setting': SettingIcon,
  'el-icon-s-grid': ViewModuleIcon,
  'el-icon-s-marketing': ChartLineIcon,
  'el-icon-s-order': ViewListIcon,
  'el-icon-s-promotion': DiscountIcon,
  'el-icon-star-on': StarFilledIcon,
  'el-icon-s-tools': ToolsIcon,
  'el-icon-s-unfold': UnfoldMoreIcon,
  'el-icon-tickets': TicketIcon,
  'el-icon-time': TimeIcon,
  'el-icon-user': UserIcon,
  'el-icon-user-solid': UserCircleIcon,
}

const iconComponent = computed(() => {
  return iconMap[props.name] || null
})
</script>
